title: TV Online Malaysia - Nonton Live Streaming Gratis HD
description: Platform nonton TV Malaysia online gratis. Streaming Astro Ria, TV3, TV9, dan saluran populer lainnya dengan kualitas HD tanpa buffering.
url: "https://goomalay.github.io" 
author: Admin TVOnline
logo: /assets/images/logo.png

# SEO & Social Media
social:
  name: TVOnlineMalaysia
  links:
    - https://facebook.com/tvonlinemy
    - https://twitter.com/tvonlinemy

# Plugins untuk Kecepatan & SEO
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist

# Optimasi Sass
sass:
  style: compressed # Mengecilkan ukuran file CSS secara otomatis
