title: TV Malaysia Online | Tonton Semua Saluran
seo_title: TV Malaysia Online
description: Tonton semua saluran TV Malaysia secara online dengan mudah dan percuma.
url: "https://goomalay.github.io" # Masukkan URL Anda di sini
baseurl: "" 

author: Admin TV Online
lang: ms-MY
permalink: /:title/ # Lebih SEO Friendly tanpa tahun

# Build settings
markdown: kramdown
include:
  - _pages
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

paginate: 12
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 12        # Berapa post yang muncul di satu halaman
paginate_path: "/page:num/" # Folder hasil pagination
